### ISSUE TITLE
incorrect use of typename within a template<>

### ISSUE THREAD

**Issue by ghost** [fgoujeon/scalpel#1]
Using typename to disambiguate is required whenever some type will not be known until instantiation time. But when the surrounding template is a full specialization (thus, it is prefixed by template<>), there is no ambiguity and the typename prefixing is an error. GCC 4.4 complains about that with the following file:
src/scalpel/cpp/detail/semantic_analysis/get_members.cpp
Patch suggested:
<patch>
diff --git a/src/scalpel/cpp/detail/semantic_analysis/get_members.cpp b/src/scalpel/cpp/detail/semantic_analysis/get_members.cpp
index f768450..32d801e 100644
--- a/src/scalpel/cpp/detail/semantic_analysis/get_members.cpp
+++ b/src/scalpel/cpp/detail/semantic_analysis/get_members.cpp
@@ -39,7 +39,7 @@ struct get_declarative_region_members_impl: public utility::static_visitor<typen

 #define GENERATE_SIMPLE_GET_MEMBERS_SPECIALIZATION(PARENT_TYPE, MEMBER_TYPE, PARENT_MEMBER_FUNCTION) \
 template<> \
-typename get_members_type_traits<semantic_entities::MEMBER_TYPE>::return_type \
+get_members_type_traits<semantic_entities::MEMBER_TYPE>::return_type \
 get_members<semantic_entities::MEMBER_TYPE, std::shared_ptr<semantic_entities::PARENT_TYPE>>(std::shared_ptr<semantic_entities::PARENT_TYPE> parent) \
 { \
        return parent->PARENT_MEMBER_FUNCTION(); \
@@ -47,7 +47,7 @@ get_members<semantic_entities::MEMBER_TYPE, std::shared_ptr<semantic_entities::P

 #define GENERATE_EMPTY_GET_MEMBERS_SPECIALIZATION(PARENT_TYPE, MEMBER_TYPE) \
 template<> \
-typename get_members_type_traits<semantic_entities::MEMBER_TYPE>::return_type \
+get_members_type_traits<semantic_entities::MEMBER_TYPE>::return_type \
 get_members<semantic_entities::MEMBER_TYPE, std::shared_ptr<semantic_entities::PARENT_TYPE>>(std::shared_ptr<semantic_entities::PARENT_TYPE>) \
 { \
        return get_members_type_traits<semantic_entities::MEMBER_TYPE>::return_type(); \
@@ -55,7 +55,7 @@ get_members<semantic_entities::MEMBER_TYPE, std::shared_ptr<semantic_entities::P

 #define GENERATE_DECLARATIVE_REGION_VARIANT_GET_MEMBERS_SPECIALIZATION(PARENT_TYPE, MEMBER_TYPE) \
 template<> \
-typename get_members_type_traits<semantic_entities::MEMBER_TYPE>::return_type \
+get_members_type_traits<semantic_entities::MEMBER_TYPE>::return_type \
 get_members<semantic_entities::MEMBER_TYPE, semantic_entities::PARENT_TYPE>(semantic_entities::PARENT_TYPE parent) \
 { \
        get_declarative_region_members_impl<semantic_entities::MEMBER_TYPE> impl; \

</end patch>

Best regards,
Zara

**Comment by fgoujeon** [comment]
It's fixed. Thank you Zara.

Strangely, GCC 4.5 doesn't complain about it…
