### ISSUE TITLE
virtual memory exhausted trying to build

### ISSUE THREAD

**Issue by hugoArregui** [fgoujeon/scalpel#3]
My system:

Arch linux
cmake 2.8.7
gcc 4.6.2
GNU make 3.82

$ cmake . -G"Unix Makefiles"
$ make

consumes 100% of the CPU, and lot of mem before "virtual memory exhausted" is throwed.

Thanks.

**Comment by fgoujeon** [comment]
Hi Hugo,

How big are your RAM and your swap?

**Comment by hugoArregui** [comment]
Hi,

RAM: 2gb
swap: 128m

**Comment by fgoujeon** [comment]
Try to grow your swap to 2GB and tell me if it's better.
